version: "3"
services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: proyecto-integrador-app
        ports:
        - "8187:3001"
        volumes:
        - "/app/node_modules"
        - "./:/app"
        networks: 
            - app-network
    db:
        image: mysql:5.7.22
        container_name: proyecto-integrador-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3320:3306"
        environment:
            MYSQL_DATABASE: proyecto
            MYSQL_ROOT_PASSWORD: proyecto
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - /docker-volumes/proyecto:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network


networks:
    app-network:
        driver: bridge